# Generated by Django 5.2.8 on 2025-11-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employee',
            new_name='employee_data',
        ),
    ]
