# Generated by Django 5.2.8 on 2025-12-01 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_userdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserData',
            new_name='user',
        ),
    ]
