# Generated by Django 5.2.8 on 2025-12-03 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_rename_userdata_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='checkbox_check',
            new_name='terms',
        ),
    ]
