# Generated by Django 5.2.8 on 2025-12-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_rename_checkbox_check_user_terms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employee_data',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
